"""add message column to logs

Revision ID: 4829a4c6cbc6
Revises: b2db139f7b9b
Create Date: 2026-07-15 15:42:19.915042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4829a4c6cbc6'
down_revision: Union[str, Sequence[str], None] = 'b2db139f7b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'message')
    # ### end Alembic commands ###
